#!/usr/bin/env ruby
lib = File.expand_path(File.join(__dir__, '..', 'lib'))
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'yubikey/neo/cli/yubioath'
Yubikey::Neo::CLI::YubiOATH.start
